// Package sets implements a generic set type for any comparable type
package sets

import (
	"iter"
	"maps"
)

// Set is the implementation of the set of values of type T
type Set[T comparable] map[T]struct{}

// New creates and returns a new empty set
func New[T comparable]() Set[T] {
	return make(Set[T])
}

// Values returns a slice containing the values of s
func (s Set[T]) Values() []T {
	vals := make([]T, 0, len(s))
	for k := range s {
		vals = append(vals, k)
	}
	return vals
}

// Clone creates and returns a copy of the set s
func (s Set[T]) Clone() Set[T] {
	return maps.Clone[Set[T]](s)
}

// Clear evaluates s ← ∅ and returns s
func (s Set[T]) Clear() Set[T] {
	for k := range s {
		delete(s, k)
	}
	return s
}

// Add inserts the values v into s and returns s
func (s Set[T]) Add(v ...T) Set[T] {
	for _, v := range v {
		s[v] = struct{}{}
	}
	return s
}

// AddIter inserts the values generated by q into s and returns s
func (s Set[T]) AddIter(q iter.Seq[T]) Set[T] {
	for v := range q {
		s[v] = struct{}{}
	}
	return s
}

// Remove removes the values v from s and returns s
func (s Set[T]) Remove(v ...T) Set[T] {
	for _, v := range v {
		delete(s, v)
	}
	return s
}

// RemoveIter removes the values generated by q from s and returns s
func (s Set[T]) RemoveIter(q iter.Seq[T]) Set[T] {
	for v := range q {
		delete(s, v)
	}
	return s
}

// Union evaluates s ← s ∪ w and returns s
func (s Set[T]) Union(w Set[T]) Set[T] {
	maps.Copy(s, w)
	return s
}

// Intersect evaluates s ← s ∩ w and returns s
func (s Set[T]) Intersect(w Set[T]) Set[T] {
	for k := range s {
		if _, ok := w[k]; !ok {
			delete(s, k)
		}
	}
	return s
}

// Diff evaluates s ← s ∖ w and returns s
func (s Set[T]) Diff(w Set[T]) Set[T] {
	for k := range w {
		delete(s, k)
	}
	return s
}

// SymDiff evaluates s ← s ∆ w and returns s
func (s Set[T]) SymDiff(w Set[T]) Set[T] {
	for k := range w {
		if _, ok := s[k]; ok {
			delete(s, k)
		} else {
			s[k] = struct{}{}
		}
	}
	return s
}

// Equal returns s = w
func (s Set[T]) Equal(w Set[T]) bool {
	if len(s) != len(w) {
		return false
	}
	for k := range s {
		if _, ok := w[k]; !ok {
			return false
		}
	}
	return true
}

// Subset returns s ⊆ w
func (s Set[T]) Subset(w Set[T]) bool {
	for k := range s {
		if _, ok := w[k]; !ok {
			return false
		}
	}
	return true
}

// In returns v ∈ s
func (s Set[T]) In(v T) (ok bool) {
	_, ok = s[v]
	return
}

// Any returns ∃x ∈ v: x ∈ s
func (s Set[T]) Any(v ...T) (ok bool) {
	for _, v := range v {
		if _, ok = s[v]; ok {
			return
		}
	}
	return
}

// All returns ∀x ∈ v: x ∈ s
func (s Set[T]) All(v ...T) bool {
	for _, v := range v {
		if _, ok := s[v]; !ok {
			return false
		}
	}
	return true
}
